url: https://jasmcole.github.io
baseurl:

# Site settings
title: jasmcole.github.io
email: jcole730@gmail.com
description: "The personal website of Jason Cole."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: c70000
  secondary: 111111
  secondary-dark: 333


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope
    url: mailto:jcole730@gmail.com
  - title: mortar-board
    url: http://www3.imperial.ac.uk/johnadamsinstitute/team
  - title: wordpress
    url: http://www.jasmcole.com
  - title: google-plus
    url: https://plus.google.com/112991282536415123341/posts
  - title: twitter
    url: http://twitter.com/jasmcole
  - title: github
    url: http://github.com/jasmcole

# Build settings
markdown: kramdown
permalink: pretty
